"""add submit_datetime column

Revision ID: b1acb7c5f9bf
Revises: 3ee47a319b67
Create Date: 2018-12-03 12:23:18.917494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1acb7c5f9bf'
down_revision = '3ee47a319b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('submit_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'submit_datetime')
    # ### end Alembic commands ###
